### ISSUE TITLE
There is no option available in custom chart development to make use of color styles

### ISSUE THREAD

**Issue by nsdevaraj** [SAP/lumira-extension-viz#1]
Lumira > File > Preferences > Charts > Chart Style > Color Palette

**Comment by vamsi-id** [comment]
Nice Idea! I've raised it in the Lumira Idea Place. https://ideas.sap.com/SAPLumira/D25227

**Comment by vamsi-id** [comment]
We now have the option to use color palettes in custom charts,
http://scn.sap.com/community/lumira/blog/2015/04/10/applying-color-palettes-to-lumira-visualization-extensions
