### ISSUE TITLE
Not working on 1.29.3

### ISSUE THREAD

**Issue by jamiehylton** [SAP/lumira-extension-viz#20]
I get error when trying to open in Lumira 1.29.3 and a SAP note that it refers to:
2111803 - Error HDB 00053: Unrecognized document format. This document may be corrupted <path to lums file>

**Comment by AnnieMT** [comment]
Hi @jamiehylton 

What exactly are you trying to open? Which extension? Can you give a bit more detail on the steps that you've taken before you got this error?

Thanks,
Annie

**Comment by jamiehylton** [comment]
Hi Annie!

Sorry, I'm a bit of a newbie...

It was the Force_Diagram I tried to do in Lumira, Extensions, "Manual Installation".

I've also just discovered the SAP Web IDE VizPacker, and I can't seem to open it in there either.

Jamie

**Comment by jamiehylton** [comment]
SORRY!  It was being being an idiot, and downloading corrupt file.

Works now.  Thanks!

**Comment by AnnieMT** [comment]
Hi Jamie,

I was just composing a long message with detailed instructions. But glad to see you have it working now. No worries. 

Thanks for reaching out!

Annie

**Comment by abinjacob** [comment]
To use Lumira DA extension SQL Server Analysis Services we need to download 2 Microsoft DLLs:
· Interop.ADODB.dll
· Interop.ADOMD.dll

I could find Interop.ADODB.dll from C/program files.Please help me where can I get  the dll Interop.ADOMD.dll from?
