### ISSUE TITLE
Cannot reproduce the sample : Timeline Bar_legend.lums

### ISSUE THREAD

**Issue by hanssegers** [SAP/lumira-extension-viz#22]
Dear all,

I do not succeed configuring the "Timeline Legend Chart" in the sample "Timeline Bar_legend.lums".
Only a limited set of data is displayed, see attached screenshot.
Version : Lumira Desktop 1.31
Extension : sap.viz.ext.timelinelegend1.0.6.zip

![timeline](https://cloud.githubusercontent.com/assets/20163826/16374142/731307ee-3c55-11e6-874e-5685cb4045a8.jpg)

Thanks for sharing your ideas !

Hans

**Comment by AnnieMT** [comment]
Hi @hanssegers 

This works for me. Perhaps you can retry again by creating a new Lums file.
![scroll](https://cloud.githubusercontent.com/assets/7472704/16425904/941824b2-3d1b-11e6-98ef-5ea74cea0607.png)

**Comment by hanssegers** [comment]
Thanks Annie for the reply.
I found the solution. In the Prepare Room, you have to set as Display Format for the "Start Date" and "End Date" : MM-DD-YY (and not : DD-MM-YY)

**Comment by AnnieMT** [comment]
Great! @hanssegers 
The dataset actually has the Start Date (2) and End Date (2) columns that have the correct date format.
