### ISSUE TITLE
Lumira Sankey diagram

### ISSUE THREAD

**Issue by nejjjones** [SAP/lumira-extension-viz#23]
Hi

I have loaded the Sankey Lumira extension & Lumira says it is succesful.  Then I cut n pasted the Business Financial flow sample data, and created the Lumira vizualization, but there is no display.

 :-(.  I get a Failed to create chart: Dimension set 0 not found' error.

Any ideas would be very welcome.  FYI Just to be sure I have the Lumira load process ok, I also loaded different Lumira extension & that works.

Thanks and regards
Nick

**Comment by nejjjones** [comment]
FYI I am using Lumira 1.30

**Comment by nejjjones** [comment]
And I loaded the Sankey Diagram.lums with the same result - no display

**Comment by AnnieMT** [comment]
Hi @nejjjones 

I just wanted to make sure that you used the correct data binding format for the Sankey diagram.i.e. Amount in Measures, Source and Target in Dimensions. Hopefully that should work.
- Annie

**Comment by nejjjones** [comment]
Good day Annie

Thanks for replying so quickly.

I am using Amount in Measures, Source and Target in Dimensions.  The Dimension error show when the Amount is moved to the value field: 
![image](https://cloud.githubusercontent.com/assets/20255999/16551671/1ef2ff14-41bb-11e6-9eb5-dd2371d14c94.png)
 Then after moving Source and Target, it gives no display:
![image](https://cloud.githubusercontent.com/assets/20255999/16551700/6cd8e284-41bb-11e6-9a75-c5c58fbed384.png)

Regards
Nick

**Comment by AnnieMT** [comment]
Hi Nick,

And what about the other dataset? Does that one work for you?

**Comment by nejjjones** [comment]
Neither work.  Note that the Energy flow dataset has the Measure called value.  Changing it to Amount, does not help

**Comment by nejjjones** [comment]
Hello Annie, sorry to pester.  Have you any further thoughts - I am rather lost ?
regards
Nick

**Comment by AnnieMT** [comment]
Hi @nejjjones 

I'm not sure why this could be happening. However, just to check, can you make sure that you have selected the corrected extension in the dropdown? And also installed the correct extension (that should show up on the extension manager). If you can confirm that, and it still doesn't work then perhaps you have to debug it in Lumira to see why the chart is not rendering.

Sorry for the late reply.
Annie

**Comment by nejjjones** [comment]
Hello Annie

Not sure what you mean by correct extension.  The process I have used is:
- download sap.viz.ext.sankey,zip from github
- start Lumira, go to file/extension manager
- Manual installation
- select the .zip & it says it has loaded

This worked for the Line chart with Zoom extension.

thanks & regards
Nick

**Comment by nejjjones** [comment]
Here is the extension manager screen:
![image](https://cloud.githubusercontent.com/assets/20255999/16701206/8df0f2c6-455e-11e6-97f1-16931f5fce72.png)

**Comment by AnnieMT** [comment]
Okay and what about in the dropdown for selecting the correct extension? This is in the chart picker section, the "Custom Charts" dropdown.

**Comment by dongpan2004** [comment]
Are you in a network where a web proxy is needed to access Internet? Note that the Sankey chart requires Internet connection to work. Either try to launch Lumira with direct Internet access, or configure the web proxy in Lumira Desktop, and try again.

**Comment by nejjjones** [comment]
OK !!!   I changed to no proxy and bingo!

Many thanks Dong and many thanks for your patience Annie !!!!

Sankey charts on demand.  Lovely lovely lovely !!

:-)
