### ISSUE TITLE
 question

### ISSUE THREAD

**Issue by TheOneBy** [SAP/lumira-extension-viz#24]
Hello, help me please.
I have custom dynamic cvom and i need some reactions from my cvom for standard property onSelect() in design studio and standart method getSelectMember. How can i do it?  

maybe Can you create examlpe?

**Comment by vamsi-id** [comment]
Could you please post your request in the Design Studio SCN forum so that other experts can look into this, You can start a new discussion at http://scn.sap.com/community/businessobjects-design-studio/content
