### ISSUE TITLE
Not able to export "Geo Maps Leaflet - SAP Lumira visualization extension" in pdf format

### ISSUE THREAD

**Issue by Vikash2402** [SAP/lumira-extension-viz#25]
Hi,
I tried to use leaflet extension in Lumira and I notices its not visible in exported pdf.
Below are the screensots for more details-

Able to see Leaflet map in Lumira 
![leaflet issue](https://cloud.githubusercontent.com/assets/7596498/17928535/c43f1400-6a18-11e6-9a43-3c5d71583710.PNG)

Not Visible in exported pdf.
![leaflet pdf](https://cloud.githubusercontent.com/assets/7596498/17928595/19291d3a-6a19-11e6-9b77-fb8d7d872489.PNG)

Final output:
[Leaflet sample .pdf](https://github.com/SAP/lumira-extension-viz/files/434539/Leaflet.sample.pdf)

Any Hint or input why its happening?

Please let me know if any further details required.

**Comment by vamsi-id** [comment]
@Vikash2402 PDF export of story pages with chart extensions is not working right now as of Lumira 1.31

**Comment by vamsi-id** [comment]
I'll close this issue here as this is a product bug. Please feel free to add your comments here, https://ideas.sap.com/D38022
